CREATE DATABASE winternews;

USE winternews;

CREATE TABLE winterao (
	id TINYINT(4) AUTO_INCREMENT PRIMARY KEY,
	titulo VARCHAR(128) NOT NULL,
	contenido TEXT NOT NULL,
	autor VARCHAR(64) NOT NULL,
	fecha DATE
);

CREATE TABLE impc (
	id TINYINT(4) AUTO_INCREMENT PRIMARY KEY,
	titulo VARCHAR(128) NOT NULL,
	contenido TEXT NOT NULL,
	autor VARCHAR(64) NOT NULL,
	fecha DATE
);